image: maven:latest
  
cache:
  paths:
    - .m2/repository

.validate: &validate
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'
    
.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify site site:stage'
  except:
    - master

deploy:jdk8:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy site site:stage'
  only:
    - master
  artifacts:
    paths:
    - target/staging


staging:
  stage: deploy
  script:
    - mv target/staging public
    - gem install dpl
    - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
  dependencies:
    - deploy:jdk8
  artifacts:
    paths:
    - public
  only:
    - master
