image: maven:latest
  
cache:
  paths:
    - .m2/repository

deploy:jdk8:
  stage: build
  script:
    - mvn -B package
    - ls
    - ls target/
  only:
    - master
  artifacts:
    paths:
    - target

#deploy:jdk8:
#  stage: test
#  script:
#    - 'mvn $MAVEN_CLI_OPTS deploy site site:stage'
#  only:
#    - master
#  artifacts:
#    paths:
#    - target

staging:
  stage: deploy
  script:
    - mv target public
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY
  dependencies:
    - deploy:jdk8
  artifacts:
    paths:
    - public
  only:
    - master
